project_id = "giotto-local-dev"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
use_pooler = false
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
upload_file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:8080"
additional_redirect_urls = ["http://localhost:8080/auth/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
security_refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template = {}

[auth.sms]
enable_signup = false
enable_confirmations = false
template = {}

[edge_runtime]
enabled = true
ip_version = "ipv6"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.validate-apple-receipt]
verify_jwt = true

[functions.validate-google-receipt]
verify_jwt = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"