// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tilhdqlyjevhewmuoxep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpbGhkcWx5amV2aGV3bXVveGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODEwNDcsImV4cCI6MjA2MTE1NzA0N30.f1OL6X1rYNuBHitEF95wI9WRqfk78YMWnUehuZDnU6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);